source "https://rubygems.org"

gem "capistrano", "~> 2.15.4"

gem "capistrano_colors"

gem "capistrano-multiconfig", "~> 0.0.4"
gem "capistrano-uptodate"
gem "capistrano-patch"
gem "capistrano-calendar"
